#!/bin/bash

PARAMS=( "$@")
PARAMS="${PARAMS[@]:2}"

TEMP_SCRIPT=$TMPDIR
TEMP_SCRIPT+="script.sh"
/bin/cat <<EOM >$TEMP_SCRIPT
cd "$1"
SCRIPT="$2"
clear
. "\$SCRIPT" $PARAMS
EOM

chmod +x $TEMP_SCRIPT
chmod +x "$2"

osascript <<END
tell application "Terminal"
    set shell to do script ""
    activate in shell
    do script ". $TEMP_SCRIPT" in shell
end tell
END
